"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown } from "lucide-react";

interface ExperienceItemProps {
  title: string;
  company: string;
  duration: string;
  description: string[];
}

const ExperienceItem: React.FC<ExperienceItemProps> = ({
  title,
  company,
  duration,
  description,
}) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <motion.div
      initial={false}
      animate={{ backgroundColor: isOpen ? "#f3f4f6" : "#ffffff" }}
      className="border-b border-gray-200 last:border-b-0 dark:border-gray-700 dark:bg-gray-800 dark:text-white"
    >
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex justify-between items-center w-full p-4 text-left focus:outline-none"
      >
        <div>
          <h3 className="text-lg font-semibold text-foreground">{title} at {company}</h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">{duration}</p>
        </div>
        <motion.div
          variants={{
            open: { rotate: 180 },
            closed: { rotate: 0 },
          }}
          transition={{ duration: 0.2 }}
          initial={false}
          animate={isOpen ? "open" : "closed"}
        >
          <ChevronDown className="text-gray-600 dark:text-gray-300" />
        </motion.div>
      </button>
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            key="content"
            initial="collapsed"
            animate="open"
            exit="collapsed"
            variants={{
              open: { opacity: 1, height: "auto" },
              collapsed: { opacity: 0, height: 0 },
            }}
            transition={{ duration: 0.3, ease: [0.04, 0.62, 0.23, 0.98] }}
            className="overflow-hidden px-4 pb-4"
          >
            <ul className="list-disc pl-5 text-gray-700 dark:text-gray-300">
              {description.map((item, index) => (
                <li key={index} className="mb-1">
                  {item}
                </li>
              ))}
            </ul>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

const Resume: React.FC = () => {
  const experienceData = [
    {
      title: "International Student Support App",
      company: "HCDE 302 & 303",
      duration: "Sep 2024 – Mar 2025",
      description: [
        "Architected a mobile application tailored for international students’ transition, leveraging social science frameworks to ground UX/UI decisions in behavioral data.",
        "Led user research to pinpoint cross-cultural adaptation challenges, successfully translating qualitative insights into high-fidelity functional requirements.",
      ],
    },
    {
      title: "Badminton Court Management System",
      company: "Personal/Course Project",
      duration: "Jan 2025 – Feb 2025",
      description: [
        "Developed an end-to-end management platform featuring automated user reservations, dynamic court scheduling, and tournament organization modules.",
        "Streamlined administrative workflows, significantly increasing court utilization rates and reducing scheduling conflicts for local sports communities.",
      ],
    },
    {
      title: "TCG Card Recycling Project",
      company: "HCDE 313",
      duration: "Mar 2025 – Jun 2025",
      description: [
        "Designed a circular economy framework for Trading Card Games (TCG) to mitigate environmental waste generated by low-value inventory.",
        "Validated sustainability feasibility through targeted user interviews and stakeholder analysis, delivering a strategic roadmap for eco-friendly practices in the gaming industry.",
      ],
    },
  ];

  return (
    <section className="py-12">
      <h2 className="text-3xl font-bold text-center mb-8 text-foreground">Projects</h2>
      <div className="max-w-3xl mx-auto bg-white shadow-md rounded-lg overflow-hidden dark:bg-gray-800">
        {experienceData.map((item, index) => (
          <ExperienceItem key={index} {...item} />
        ))}
      </div>
    </section>
  );
};

export default Resume;
